name: linkchecker

# run every day at 10:00AM UTC - 3:30PM IST
on:
  schedule:
    - cron: '0 10 * * *'

  workflow_dispatch:
    inputs:
      signozWebsiteUrl:
        description: 'SigNoz Website URL'
        type: string
        required: false

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install linkchecker
        run: |
          pip3 install linkchecker

      - name: Run linkchecker
        env:
          SIGNOZ_WEBSITE_URL: ${{ github.event.inputs.signozWebsiteUrl }}
        run: |
          set -e

          if [ -z "$SIGNOZ_WEBSITE_URL" ]; then
            SIGNOZ_WEBSITE_URL=https://signoz.io
          fi

          echo "SIGNOZ_WEBSITE_URL: $SIGNOZ_WEBSITE_URL"

          linkchecker $SIGNOZ_WEBSITE_URL
